[env]
platform = ch32v
build_flags = -Isrc
framework = noneos-sdk
upload_protocol = isp
board = genericCH32V203G6U6
board_build.clock_source = hsi+pll
board_build.f_cpu = 48000000L
;turn off the compilation of the built-in debug implementation
board_build.use_builtin_debug_code = no

[env:debug]
build_flags = ${env.build_flags} -DDEBUG=2 -DVERSION_MAJOR=\"255\" -DVERSION_MINOR=\"255\" -DVERSION_PATCH=\"255\"

[env:release]
