[env]
platform = ch32v
build_flags = -I. -D DEBUG
framework = noneos-sdk
upload_protocol = isp

[env:genericCH32V203G6U6]
board = genericCH32V203G6U6
board_build.clock_source = hsi+pll
board_build.f_cpu = 48000000L
